#!/bin/sh
set -e

version=5.0.20
hash=11f40842a56ebb17da1bbc82a21543e66108a5330ebd54ded68038a990aa071b
file=Oracle_VM_VirtualBox_Extension_Pack-$version.vbox-extpack

error ()
{
	echo "Hash mismatch $file"
	exit 1
}

# Source debconf library.
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ] ; then
	cd /usr/share/virtualbox-ext-pack
	echo "virtualbox-ext-pack: downloading: http://download.virtualbox.org/virtualbox/$version/$file"
	echo "The file will be downloaded into /usr/share/virtualbox-ext-pack"
	wget -q -N http://download.virtualbox.org/virtualbox/$version/$file
	echo "$hash  $file" | sha256sum -c > /dev/null 2>&1 || error
	vboxmanage extpack install --replace $file
fi

#DEBHELPER#
