#!/bin/sh
set -e

version=4.3.28
hash=72e101d9dc5eabeb76d1ab5bd6d2f817a11c89adfe8bb72cc5d614a2eef532d1
file=Oracle_VM_VirtualBox_Extension_Pack-$version.vbox-extpack

error ()
{
	echo "Hash mismatch $file"
	exit 1
}

# Source debconf library.
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ] ; then
        db_get virtualbox-ext-pack/license
        if [ "$RET" = true ] ; then
		cd /usr/share/virtualbox-ext-pack
		echo "virtualbox-ext-pack: downloading: http://download.virtualbox.org/virtualbox/$version/$file"
		wget -q -N http://download.virtualbox.org/virtualbox/$version/$file
		echo "$hash  $file" | sha256sum -c > /dev/null 2>&1 || error
		vboxmanage extpack install --replace $file
	else
		exit 1
	fi
fi

#DEBHELPER#
