#!/bin/sh
set -e

if [ -c /dev/vboxdrv ]; then
        vboxmanage extpack uninstall --force "Oracle VM VirtualBox Extension Pack"
        vboxmanage extpack cleanup
else
        echo "you seem to be not running the vboxdrv kernel module, the extpack uninstall will be forced."
fi

rm /usr/share/virtualbox-ext-pack/*.vbox-extpack 1>/dev/null 2>&1 # Maybe we should specify the file like in the postinst?

#DEBHELPER#
